apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
  - ../../../manifests/argocd/apps/resource-locker/base
  - ../../../manifests/argocd/apps/openshift-monitoring/base
  - ../../../manifests/argocd/apps/openshift-file-integrity/base
  - ../../../manifests/argocd/apps/openshift-logging/base
  - ../../../manifests/argocd/apps/openshift-container-storage/base
  - ../../../manifests/argocd/apps/openshift-virtualization/base
  - ../../../manifests/argocd/apps/quay/base

# patches:
#  - patches/enable-virt-emulation.yaml