apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-infra-apps
spec:
  clusterResourceWhiteList:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"