apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource-locker-app
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: "cluster-infra-apps"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-infra-apps
  source:
    path: manifests/resource-locker/base
    repoURL: https://github.com/pumphouse-p/openshift-cluster-infra-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true